# Generated by Django 5.0 on 2023-12-28 17:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="files",
            name="accept_file",
        ),
        migrations.RemoveField(
            model_name="files",
            name="denied_file",
        ),
        migrations.AddField(
            model_name="files",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Принято"), (2, "Отклонено"), (3, "На проверке")],
                default=3,
            ),
        ),
    ]
